name: Production deployment

on: 
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: whiteboard-demo
  IMAGE_REGISTRY_URL: crignitedev2022.azurecr.io  
  AZURE_CONTAINERAPPS_NAME: "whiteboard-pwa-ignite-2022"
  AZURE_RESOURCE_GROUP: Ignite_DevTools
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v1
      - name: npm install and build webpack
        run: |
          npm install
          npm run start stencil build

  Build-Docker-Image:
    runs-on: ubuntu-latest
    needs: build
    name: Build image and store in Azure Container Registry
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Docker Login"
        uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PWD }}
      - run: |
            docker build . -t ${{ env.IMAGE_REGISTRY_URL }}/board/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}
            docker push ${{ env.IMAGE_REGISTRY_URL }}/board/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}
            
  Deploy-to-Azure:
    runs-on: ubuntu-latest
    environment: 'prod'
    needs: Build-Docker-Image
    name: Deploy app to Azure Container Apps
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PWD }}

      - name: Deploy containnerapp 
        if: success()
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update -n ${{env.AZURE_CONTAINERAPPS_NAME}} -g ${{env.AZURE_RESOURCE_GROUP}} --image ${{env.IMAGE_REGISTRY_URL}}/board/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout
